# Generated by Django 4.1.7 on 2023-03-20 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_drop', models.DateTimeField(auto_now_add=True)),
                ('kurta', models.IntegerField()),
                ('pajama', models.IntegerField()),
                ('shirt', models.IntegerField()),
                ('T_shirt', models.IntegerField()),
                ('pant', models.IntegerField()),
                ('lower', models.IntegerField()),
                ('shorts', models.IntegerField()),
                ('bedsheet', models.IntegerField()),
                ('pillow_cover', models.IntegerField()),
                ('towel', models.IntegerField()),
                ('dupatta', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
