# Generated by Django 4.1.7 on 2023-03-27 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='clothe',
            fields=[
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Student_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Kurta', models.IntegerField()),
                ('Pajama', models.IntegerField()),
                ('Shirt', models.IntegerField()),
                ('T_Shirt', models.IntegerField()),
                ('Pant', models.IntegerField()),
                ('Lower', models.IntegerField()),
                ('Shorts', models.IntegerField()),
                ('Bedsheet', models.IntegerField()),
                ('Pillow_Cover', models.IntegerField()),
                ('Towel', models.IntegerField()),
                ('Dupatta', models.IntegerField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
