# Generated by Django 4.1.7 on 2023-03-27 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Kurta', models.IntegerField()),
                ('Pajama', models.IntegerField()),
                ('Shirt', models.IntegerField()),
                ('T_Shirt', models.IntegerField()),
                ('Pant', models.IntegerField()),
                ('Lower', models.IntegerField()),
                ('Shorts', models.IntegerField()),
                ('Bedsheet', models.IntegerField()),
                ('Pillow_Cover', models.IntegerField()),
                ('Towel', models.IntegerField()),
                ('Dupatta', models.IntegerField()),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
