# Generated by Django 4.1.7 on 2023-03-21 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='bedsheet',
            new_name='Bedsheet',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='date_drop',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='dupatta',
            new_name='Dupatta',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='kurta',
            new_name='Kurta',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='lower',
            new_name='Lower',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='pajama',
            new_name='Pajama',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='pant',
            new_name='Pant',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='pillow_cover',
            new_name='Pillow_Cover',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='shirt',
            new_name='Shirt',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='shorts',
            new_name='Shorts',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='student',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='T_shirt',
            new_name='T_Shirt',
        ),
        migrations.RenameField(
            model_name='clothes',
            old_name='towel',
            new_name='Towel',
        ),
    ]
