# Generated by Django 4.2 on 2023-04-24 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0003_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
