# Generated by Django 4.2 on 2023-04-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0006_alter_query_cloth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='cloth',
            new_name='Laundry_id',
        ),
        migrations.RenameField(
            model_name='query',
            old_name='problem',
            new_name='Problem',
        ),
    ]
