# Generated by Django 4.2 on 2023-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0007_rename_cloth_query_laundry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Completed', 'completed')], default='Pending', max_length=15),
        ),
    ]
